src/Entity/Auteur.php
<?php

namespace App\Entity;

use App\Repository\AuteurRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Validator\Constraints as Assert;



/**
 * @ORM\Entity(repositoryClass=AuteurRepository::class)
 * @ORM\HasLifecycleCallbacks()
 * @UniqueEntity(fields={"nom_prenom"}, message="This name exists already")
 */
class Auteur
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(name="nom_prenom", type="string", length=100, unique=true)
     * @Assert\NotNull(message="Enter the fullname")
     * @Assert\NotBlank(message="Enter the fullname")
     */
    private $nom_prenom;

    /**
     * @ORM\Column(type="string", length=1)
     * @Assert\NotNull(message="Set the sex")
     * @Assert\NotBlank(message="Set the sex")
     * @Assert\Choice({"M", "F"}, message="Invalid sex value")
     */
    private $sexe;

    /**
     * @ORM\Column(type="date")
     * @Assert\NotNull(message="Set birthDate")
     * @Assert\NotBlank(message="Set birthDate")
     * @Assert\LessThan("-15 years", message="Invalid birthDate")
     */
    private $date_de_naissance;

    /**
     * @ORM\Column(type="string", length=50)
     * @Assert\NotNull(message="Set nationality")
     * @Assert\NotBlank(message="Set nationality")
     */
    private $nationalite;

    /**
     * @ORM\ManyToMany(targetEntity=Livre::class, inversedBy="auteurs")
     */
    private $livres;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     * @Assert\Url(message="Invalid image url")
     */
    private $image;

    /**
     * @ORM\Column(type="datetime")
     */
    private $created_at;

    /**
     * @ORM\Column(type="datetime")
     */
    private $updated_at;

    public function __construct()
    {
        $this->livres = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNomPrenom(): ?string
    {
        return $this->nom_prenom;
    }

    public function setNomPrenom(string $nom_prenom): self
    {
        $this->nom_prenom = $nom_prenom;

        return $this;
    }

    public function getSexe(): ?string
    {
        return $this->sexe;
    }

    public function setSexe(string $sexe): self
    {
        $this->sexe = $sexe;

        return $this;
    }

    public function getDateDeNaissance(): ?\DateTimeInterface
    {
        return $this->date_de_naissance;
    }

    public function setDateDeNaissance(\DateTimeInterface $date_de_naissance): self
    {
        $this->date_de_naissance = $date_de_naissance;

        return $this;
    }

    public function getNationalite(): ?string
    {
        return $this->nationalite;
    }

    public function setNationalite(string $nationalite): self
    {
        $this->nationalite = $nationalite;

        return $this;
    }

    /**
     * @return Collection|Livre[]
     */
    public function getLivres(): Collection
    {
        return $this->livres;
    }

    public function addLivre(Livre $livre): self
    {
        if (!$this->livres->contains($livre)) {
            $this->livres[] = $livre;
        }

        return $this;
    }

    public function removeLivre(Livre $livre): self
    {
        $this->livres->removeElement($livre);

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(?string $image): self
    {
        $this->image = $image;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(\DateTimeInterface $updated_at): self
    {
        $this->updated_at = $updated_at;

        return $this;
    }

    /**
     * @ORM\PrePersist
     * @ORM\PreUpdate
     */
    public function updatedTimestamps(): void
    {
        $this->setUpdatedAt(new \DateTime('now'));
        if ($this->getCreatedAt() === null) {
            $this->setCreatedAt(new \DateTime('now'));
        }
    }

    public function __toString() :String {
        return $this->getNomPrenom();
    }
}

src/Entity/Livre.php
<?php

namespace App\Entity;

use App\Repository\LivreRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Validator\Constraints as Assert;



/**
 * @ORM\Entity(repositoryClass=LivreRepository::class)
 * @ORM\HasLifecycleCallbacks()
 * @UniqueEntity(fields={"isbn"}, message="This ISBN13 key exists already")
 */
class Livre
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(name="isbn", type="string", length=17, unique=true)
     * @Assert\NotBlank(message="Enter the ISBN13 key")
     * @Assert\Isbn( type="isbn13", isbn13Message="Invalid ISBN-13 key")
     */
    private $isbn;

    /**
     * @ORM\Column(type="string", length=150)
     * @Assert\Length (max=150, maxMessage="Title length should be less than 150 character")
     */
    private $titre;

    /**
     * @ORM\Column(type="integer")
     * @Assert\NotNull(message="Enter number of pages")
     * @Assert\Positive(message="Invalid number of pages")
     */
    private $nombre_pages;

    /**
     * @ORM\Column(type="date")*
     * @Assert\NotNull(message="Set publushing Date")
     * @Assert\NotBlank(message="Set publushing Date")
     * @Assert\LessThan("today", message="Invalid Date")
     */
    private $date_de_parution;

    /**
     * @ORM\Column(type="smallint")
     * @Assert\NotNull(message="Enter the mark")
     * @Assert\PositiveOrZero(message="Invalid Mark")
     * @Assert\Range(
     *      min = 0,
     *      max = 20,
     *      notInRangeMessage = "Invalid Mark, it should be between {{ min }} & {{ max }}.",
     * )
     */
    private $note;

    /**
     * @ORM\ManyToMany(targetEntity=Auteur::class, inversedBy="livres")
     * @Assert\Count(min=1, minMessage="A book must be written by one author at least")
     */
    private $auteurs;

    /**
     * @ORM\ManyToMany(targetEntity=Genre::class, inversedBy="livres")
     * @Assert\Count(min=1, minMessage="A book must belong to one genre at least")
     */
    private $genres;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $image;

    /**
     * @ORM\Column(type="datetime")
     */
    private $created_at;

    /**
     * @ORM\Column(type="datetime")
     */
    private $updated_at;

    public function __construct()
    {
        $this->auteurs = new ArrayCollection();
        $this->genres = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getIsbn(): ?string
    {
        return $this->isbn;
    }

    public function setIsbn(string $isbn): self
    {
        $this->isbn = $isbn;

        return $this;
    }

    public function getTitre(): ?string
    {
        return $this->titre;
    }

    public function setTitre(string $titre): self
    {
        $this->titre = $titre;

        return $this;
    }

    public function getNombrePages(): ?string
    {
        return $this->nombre_pages;
    }

    public function setNombrePages(string $nombre_pages): self
    {
        $this->nombre_pages = $nombre_pages;

        return $this;
    }

    public function getDateDeParution(): ?\DateTimeInterface
    {
        return $this->date_de_parution;
    }

    public function setDateDeParution(\DateTimeInterface $date_de_parution): self
    {
        $this->date_de_parution = $date_de_parution;

        return $this;
    }

    public function getNote(): ?int
    {
        return $this->note;
    }

    public function setNote(int $note): self
    {
        $this->note = $note;

        return $this;
    }

    /**
     * @return Collection|Auteur[]
     */
    public function getAuteurs(): Collection
    {
        return $this->auteurs;
    }

    public function addAuteur(Auteur $auteur): self
    {
        if (!$this->auteurs->contains($auteur)) {
            $this->auteurs[] = $auteur;
            $auteur->addLivre($this);
        }

        return $this;
    }

    public function removeAuteur(Auteur $auteur): self
    {
        if ($this->auteurs->removeElement($auteur)) {
            $auteur->removeLivre($this);
        }

        return $this;
    }

    /**
     * @return Collection|Genre[]
     */
    public function getGenres(): Collection
    {
        return $this->genres;
    }

    public function addGenre(Genre $genre): self
    {
        if (!$this->genres->contains($genre)) {
            $this->genres[] = $genre;
        }

        return $this;
    }

    public function removeGenre(Genre $genre): self
    {
        $this->genres->removeElement($genre);

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(?string $image): self
    {
        $this->image = $image;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(\DateTimeInterface $updated_at): self
    {
        $this->updated_at = $updated_at;

        return $this;
    }

    /**
     * @ORM\PrePersist
     * @ORM\PreUpdate
     */
    public function updatedTimestamps(): void
    {
        $this->setUpdatedAt(new \DateTime('now'));
        if ($this->getCreatedAt() === null) {
            $this->setCreatedAt(new \DateTime('now'));
        }
    }
}

src/Controller/LivreController.php
<?php

namespace App\Controller;

use App\Entity\Livre;
use App\Form\LivreType;
use App\Repository\AuteurRepository;
use App\Repository\GenreRepository;
use App\Repository\LivreRepository;
use Doctrine\ORM\EntityManagerInterface;
use Doctrine\ORM\Query\Expr;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Form\FormError;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class LivreController extends AbstractController
{
    /**
     * @Route("/books", name="livre_index", methods={"GET"})
     */
    public function index(LivreRepository $livreRepository, GenreRepository $genreRepository, AuteurRepository $auteurRepository, Request $request, PaginatorInterface $paginator): Response
    {
        $this->denyAccessUnlessGranted("IS_AUTHENTICATED_FULLY");
        $search = trim($request->get('search'));
        $edate = trim($request->get('edate'));
        $sdate = trim($request->get('sdate'));

        $authors = $request->get('authorsIds');
        $genresIds = $request->get('genresIds');
        $genresObject = $genresIds? json_decode($genresIds):[];
        $authorsObject = $authors? json_decode( $authors ):[];
        $genres = $genreRepository->createQueryBuilder('g')->select(['g.id', 'g.nom'])->addSelect("COUNT(l.id) as livresnbr ")->leftJoin('g.livres', 'l', Expr\Join::WITH, null)->groupBy('g.id')->orderBy('livresnbr', 'desc')->setMaxResults(14)->getQuery()->getResult();
        $submitted = strlen($request->get('submitted'))>0;
        $submitted &= ( strlen($search.$edate.$sdate)>0 || strlen($authors)>0  || strlen($genresIds)>0 );


        if( !$this->dateIsValid($sdate) )
            $sdate = null;
        if( !$this->dateIsValid($edate) )
            $edate = null;

        if( is_array($genresObject) )
            for( $i=0; $i<count($genresObject); $i++)
                $genresObject[$i] = intval($genresObject[$i]);
        else
            $genresObject = [];

        $authorsIDS = [];
        if( is_array($authorsObject) )
            for( $i=0; $i<count($authorsObject); $i++)
                $authorsIDS[] = intval($authorsObject[$i]);
        if( $submitted )
            $booksQuery = $livreRepository->deepSearch( $search, $sdate, $edate, $genresObject, $authorsIDS) ;
        else
            $booksQuery =$livreRepository->findAllQuery();

        $authorsAsTags  = [];
        foreach( $authorsIDS as $id){
            $author = $auteurRepository->find($id);
            $authorsAsTags [] = (Object) [ "value"=>$author->getId()."", 'nom_prenom' =>$author->getNomPrenom(), 'image'=>$author->getImage() ];
        }

        $books = $paginator->paginate(
            $booksQuery,
            $request->query->getInt('page', 1), /*page number*/
            10 /*limit per page*/
        );

        return $this->render('livre/usernavigation.html.twig', [
            'books' => $books,
            'genres' => $genres,
            'search' => $search,
            'submitted' => $submitted ,
            'genresIds' => $genresObject,
            'authors'=> $authorsAsTags,
            'authorsIds'=> $authorsIDS,
            'edate' => $edate,
            'sdate' => $sdate,
            'order'=> $request->get('order')
        ]);
    }



    private function dateIsValid($date, $format = 'Y-m-d')
    {
        $d =  \DateTime::createFromFormat($format, $date);
        return $d && $d->format($format) === $date;
    }

    /**
     * @Route("/cp/books/new", name="livre_new", methods={"GET", "POST"})
     */
    public function new(Request $request, EntityManagerInterface $entityManager, GenreRepository $genreRepository, AuteurRepository $auteurRepository): Response
    {
        $livre = new Livre();
        $form = $this->createForm(LivreType::class, $livre);
        $form->handleRequest($request);
        /*
        $authorsIds = $request->get('auteurs');
        $genresIds = $request->get('genresIds');

        $genresObject = [];
        if( $genresIds ){
            $genresIds = json_decode( $genresIds );
            $genres = $genreRepository->createQueryBuilder('g')->where('g.id in (:ids)')->setParameter('ids', $genresIds)->getQuery()->getResult();
            foreach ( $genres as $genre){
                $genresObject [] = [ 'value' =>$genre->getId(), 'nom'=>$genre->getNom()];
            }
        }
        else
            $genresIds = [];

        $authorsObject = [];
        if( $authorsIds ){
            $authorsIds = json_decode($authorsIds);
            $authors = $auteurRepository->createQueryBuilder('a')->where(' a.id in (:ids)')->setParameter('ids', $authorsIds)->getQuery()->getResult();
            foreach( $authors as $author)
                $authorsObject [] = [ 'value'=>$author->getId(), 'nom_prenom'=>$author->getNomPrenom(), 'image'=>$author->getImage() ];
        }else
            $authorsIds = [];
        */
        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($livre);
            $entityManager->flush();
            $this->addFlash('created', 'true');
            return $this->redirectToRoute('livre_show', [ 'id'=>$livre->getId()], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('livre/new.html.twig', [
            'livre' => $livre,
            'form' => $form,
            /*
            'authorsIds' => $authorsIds,
            'authors' => $authorsObject,
            'genresIds' => $genresIds,
            'genres' => $genresObject
            */
        ]);
    }

    /**
     * @Route("/books/{id}", name="livre_show", methods={"GET"})
     */
    public function show(Livre $livre): Response
    {
        $this->denyAccessUnlessGranted("IS_AUTHENTICATED_FULLY");
        return $this->render('livre/show.html.twig', [
            'book' => $livre,
        ]);
    }

    /**
     * @Route("/cp/books/{id}/edit", name="livre_edit", methods={"GET", "POST"})
     */
    public function edit(Request $request, Livre $livre, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(LivreType::class, $livre);
        $form->handleRequest($request);


        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();
            $this->addFlash('editted', 'true');
            $this->addFlash('editted', 'true');
            return $this->redirectToRoute('livre_show', [ 'id'=>$livre->getId()], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('livre/edit.html.twig', [
            'book' => $livre,
            'form' => $form,
            /*
            'authorsIds' => [],
            'authors' => [],
            'genresIds' => [],
            'genres' => []
            */
        ]);
    }

    /**
     * @Route("/cp/books/{id}", name="livre_delete", methods={"POST"})
     */
    public function delete(Request $request, Livre $livre, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$livre->getId(), $request->request->get('_token'))) {
            $entityManager->remove($livre);
            $entityManager->flush();
            $this->addFlash('deleted', $livre->getTitre());
        }

        return $this->redirectToRoute('cp_livre_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/livre/_delete_form.html.twig
<form method="post" style="display: inline-block; width: fit-content; margin-left: auto;" action="{{ path('livre_delete', {'id': book.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ book.id) }}">
    <button class="ui button btn red" type="submit"> <i class="trash alternate icon"></i> Delete</button>
</form>

templates/livre/index.html.twig
{% extends 'base.html.twig' %}

{% block title %} BookStore | CP : Books {% endblock %}

{% block body %}
    <div class="contentWrapper">

        <div class="ui segment sixteen  column wide items" style="padding: 1em 1.5em; border: 1px solid gray; background-color: #fffffdc7;">
            <h5 class="ui header customClass pb-0">
                <a href="{{ path("cp_index") }}"> <i class="icon left arrow" ></i> Go Back to ControlPanel  </a>
            </h5>
            <h1 class="ui header center aligned customClass pt-0 violet huge"> Books management </h1>
        </div>

        <div class="ui segment sixteen  column wide items" style="padding: 1em 1.5em; border: 1px solid gray; background-color: #fffffdc7;">
            <div class="ui grid three column">
                <div class="ui column left floated">
                    <form action="{{ path('cp_livre_index') }}" method="get">
                        <div class="ui action input fluid">
                            <input type="text" name="search" maxlength="50" value="{{ search }}" placeholder="Search with title, ISBN...">
                            {% if search|length>0 %}
                                <a href="{{ path('cp_livre_index') }}" class="ui icon button negative">
                                    <i class="times icon"></i>
                                </a>
                            {% endif %}
                            <button type="submit" class="ui icon button teal">
                                <i class="search icon"></i>
                            </button>
                        </div>
                    </form>
                </div>
                <div class="column right floated customClass text-right">
                    <a href="{{ path('livre_new') }}" class="ui button positive"> <i class="icon plus"></i> Create new </a>
                </div>
            </div>


            <table class="ui selectable striped customClass table center middle aligned">
                <thead>
                    <tr>
                        <th><strong> # </strong></th>
                        <th>{% if books.isSorted('l.isbn') %}
                            <u class="purple">
                                {{ knp_pagination_sortable(books, 'ISBN13', 'l.isbn') }}
                            </u>
                            <i class="icon {{ order is same as ('asc')? 'chevron up':'chevron down' }}" ></i>
                            {% else %}
                                {{ knp_pagination_sortable(books, 'ISBN13', 'l.isbn') }}
                            {% endif %}
                        </th>
                        <th>Title</th>
                        <th>
                            {% if books.isSorted('l.nombre_pages') %}
                            <u class="purple">
                                {{ knp_pagination_sortable(books, 'Number of pages', 'l.nombre_pages') }}
                            </u>
                            <i class="icon {{ order is same as ('asc')? 'chevron up':'chevron down' }}" ></i>
                            {% else %}
                                {{ knp_pagination_sortable(books, 'Number of pages', 'l.nombre_pages') }}
                            {% endif %}
                        </th>
                        <th>
                            {% if books.isSorted('l.date_de_parution') %}
                                <u class="purple">
                                    {{ knp_pagination_sortable(books, 'Publishing date', 'l.date_de_parution') }}
                                </u>
                                <i class="icon {{ order is same as ('asc')? 'chevron up':'chevron down' }}" ></i>
                            {% else %}
                                {{ knp_pagination_sortable(books, 'Publishing date', 'l.date_de_parution') }}
                            {% endif %}
                        </th>
                        <th>
                            {% if books.isSorted('l.note') %}
                                <u class="purple">
                                    {{ knp_pagination_sortable(books, 'Rating', 'l.note') }}
                                </u>
                                <i class="icon {{ order is same as ('asc')? 'chevron up':'chevron down' }}" ></i>
                            {% else %}
                                {{ knp_pagination_sortable(books, 'Rating', 'l.note') }}
                            {% endif %}
                        </th>
                        <th>Actions</th>
                    </tr>
                </thead>
                <tbody>
                {% set i=0 %}
                {% for livre in books %}
                    {% set i=1+i %}
                    <tr>
                        <td><strong> {{ (currentPage-1)*25+i }} </strong></td>
                        <td>{{ livre.isbn }}</td>
                        <td>{{ livre.titre }}</td>
                        <td>{{ livre.nombrePages }}</td>
                        <td>{{ livre.dateDeParution ? livre.dateDeParution|date('Y-m-d') : '' }}</td>
                        <td>{{ livre.note }}</td>
                        <td>
                            <a href="{{ path('livre_show', {'id': livre.id}) }}" title="view">
                                <i class="icon eye teal"> </i>
                            </a>
                            <a href="{{ path('livre_edit', {'id': livre.id}) }}" title="Edit">
                                <i class="pencil alternate icon olive"></i>
                            </a>
                        </td>
                    </tr>
                {% else %}
                    <tr>
                        <td colspan="7">no records found</td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
        {% if books|length>0 %}
            <div class="ui segment fourteen column wide center aligned" style=" margin-bottom: 2em !important; border: 1px solid gray; background-color: #fffffdc7;">
                {{ knp_pagination_render(books) }}
            </div>
        {% endif %}

    </div>
{% endblock %}

templates/livre/show.html.twig
{% extends 'base.html.twig' %}

{% block title %} BookStore | book : {{ book.titre }}  {% endblock %}

{% block body %}
    <div class="contentWrapper" style="padding: 2em 1em;">


        <div class="ui segment sixteen column wide items" style="padding: 1em; border: 1px solid gray; background-color: #fffffdc7;">
            <div style="display: flex;align-content: center;justify-content: space-between;align-items: center;">
                <h5 class="ui header customClass pb-0 left aligned">
                    <a href="{{ path("livre_index") }}"> <i class="icon left arrow" ></i> Go Back to books list  </a>
                </h5>

                {% if is_granted('ROLE_ADMIN') %}
                    <div>
                        <a href="{{ path('cp_livre_index') }}" class="ui button orange" style="display: inline-block; width: fit-content;" > <i class="list icon"></i>  list </a>
                        <a href="{{ path('livre_edit', {'id': book.id}) }}" class="ui button olive" style="display: inline-block; width: fit-content;" > <i class="edit icon"></i> Edit </a>
                        {{ include('livre/_delete_form.html.twig') }}
                    </div>
                {% endif %}
            </div>
        </div>

        <div class="ui segment sixteen  column wide items" style="padding: 1em 1.5em; margin-top: 12px; margin-bottom: 3em; border: 1px solid gray; background-color: #fffffdc7;">
            <div class="ui items">
                <div class="item">
                    <div class="image" style="position: relative; width: unset; height: 700px;">
                        <img src="{{ book.image }}" style=" width: unset; height: 100%;">
                    </div>
                    <div class="content" style="display: flex; flex-direction: column; align-items: center; justify-content: center;">

                        <h6 class="meta meta" style="align-self: start; padding-bottom: 0.9em; text-decoration: underline;"> <strong> TITLE : </strong> </h6>
                        <h1 class="ui header center aligned big " style="padding-bottom: 1.8em;">  {{ book.titre }} </h1>

                        <div style="padding: 0px 18px; width: 100%;" >
                            <h6 class="meta meta" style="align-self: start; padding-bottom: 0.6em; text-decoration: underline;"> <strong> PAGES : </strong> </h6>
                            <h3 class="ui header center aligned big " style="padding-bottom: 1.8em;">  {{ book.nombrePages }} Pages </h3>

                            <h6 class="meta meta" style="align-self: start; padding-bottom: 0.6em; text-decoration: underline;"> <strong> PUBLISHING DATE : </strong> </h6>
                            <h3 class="ui header center aligned big " style="padding-bottom: 1.8em;">  {{ book.dateDeParution|date('d/m/Y') }}  </h3>

                            <h6 class="meta meta" style="align-self: start; padding-bottom: 0.6em; text-decoration: underline;"> <strong> RATING : </strong> </h6>
                            <h3 class="ui header center aligned big " style="padding-bottom: 1.8em;">  <strong> {{ book.note }}/20 </strong> </h3>

                            <h6 class="meta meta" style="align-self: start; padding-bottom: 0.6em; text-decoration: underline;"> <strong> ISBN13 CODE : </strong> </h6>
                            <h3 class="ui header center aligned big " style="padding-bottom: 1.8em;"> {{ book.isbn }} </h3>

                            <h6 class="meta meta" style="align-self: start; padding-bottom: 0.6em; text-decoration: underline;"> <strong> GENRES : </strong> </h6>
                            {% set classnames = [ 'olive', 'grey', 'violet', 'purple', 'teal', 'blue', 'green', 'orange', 'brown', 'yellow', 'red'] %}
                            <h5 class="ui header center aligned big " style="padding-bottom: 1.8em;">
                                {% for genre in book.genres %}
                                    <a class="ui label {{ random(classnames) }}" href="{{ path('genre_show', {'id':genre.id}) }}" target="_blank"> {{ genre.nom }} </a>
                                {% endfor %}
                            </h5>


                            <h6 class="meta meta" style="align-self: start; padding-bottom: 0.6em; text-decoration: underline;"> <strong> AUTHORS : </strong> </h6>
                            <h5 class="ui header center aligned big " style="padding-bottom: 1.8em;">
                                {% for auteur in book.auteurs %}
                                    <a class="ui label" href="{{ path('auteur_show', { id: auteur.id}) }}" target="_blank" >
                                        <img src="{{ auteur.image }}" class="ui right spaced avatar image">
                                        {{ auteur.nomPrenom }}
                                    </a>
                                {% endfor %}
                            </h5>
                        </div>
                        {% if is_granted('ROLE_ADMIN') %}
                            <div class="extra brown">
                                Created in :  {{ book.createdAt|date('d/m/Y') }} , and editted last time in {{ book.updatedAt|date('d/m/Y') }}
                            </div>
                        {% endif %}
                        {% if app.flashes('editted')|length>0 %}
                            <div class="ui green message">
                                <div class="header" style="text-align: center;">
                                    Book changes were successfuly saved
                                </div>
                            </div>
                        {% endif %}
                        {% if app.flashes('created')|length>0 %}
                            <div class="ui green message">
                                <div class="header" style="text-align: center;">
                                    Book created successfuly
                                </div>
                            </div>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}