src/Entity/Auteur.php
<?php

namespace App\Entity;

use App\Repository\AuteurRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Validator\Constraints as Assert;



/**
 * @ORM\Entity(repositoryClass=AuteurRepository::class)
 * @ORM\HasLifecycleCallbacks()
 * @UniqueEntity(fields={"nom_prenom"}, message="This name exists already")
 */
class Auteur
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(name="nom_prenom", type="string", length=100, unique=true)
     * @Assert\NotNull(message="Enter the fullname")
     * @Assert\NotBlank(message="Enter the fullname")
     */
    private $nom_prenom;

    /**
     * @ORM\Column(type="string", length=1)
     * @Assert\NotNull(message="Set the sex")
     * @Assert\NotBlank(message="Set the sex")
     * @Assert\Choice({"M", "F"}, message="Invalid sex value")
     */
    private $sexe;

    /**
     * @ORM\Column(type="date")
     * @Assert\NotNull(message="Set birthDate")
     * @Assert\NotBlank(message="Set birthDate")
     * @Assert\LessThan("-15 years", message="Invalid birthDate")
     */
    private $date_de_naissance;

    /**
     * @ORM\Column(type="string", length=50)
     * @Assert\NotNull(message="Set nationality")
     * @Assert\NotBlank(message="Set nationality")
     */
    private $nationalite;

    /**
     * @ORM\ManyToMany(targetEntity=Livre::class, inversedBy="auteurs")
     */
    private $livres;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     * @Assert\Url(message="Invalid image url")
     */
    private $image;

    /**
     * @ORM\Column(type="datetime")
     */
    private $created_at;

    /**
     * @ORM\Column(type="datetime")
     */
    private $updated_at;

    public function __construct()
    {
        $this->livres = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNomPrenom(): ?string
    {
        return $this->nom_prenom;
    }

    public function setNomPrenom(string $nom_prenom): self
    {
        $this->nom_prenom = $nom_prenom;

        return $this;
    }

    public function getSexe(): ?string
    {
        return $this->sexe;
    }

    public function setSexe(string $sexe): self
    {
        $this->sexe = $sexe;

        return $this;
    }

    public function getDateDeNaissance(): ?\DateTimeInterface
    {
        return $this->date_de_naissance;
    }

    public function setDateDeNaissance(\DateTimeInterface $date_de_naissance): self
    {
        $this->date_de_naissance = $date_de_naissance;

        return $this;
    }

    public function getNationalite(): ?string
    {
        return $this->nationalite;
    }

    public function setNationalite(string $nationalite): self
    {
        $this->nationalite = $nationalite;

        return $this;
    }

    /**
     * @return Collection|Livre[]
     */
    public function getLivres(): Collection
    {
        return $this->livres;
    }

    public function addLivre(Livre $livre): self
    {
        if (!$this->livres->contains($livre)) {
            $this->livres[] = $livre;
        }

        return $this;
    }

    public function removeLivre(Livre $livre): self
    {
        $this->livres->removeElement($livre);

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(?string $image): self
    {
        $this->image = $image;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(\DateTimeInterface $updated_at): self
    {
        $this->updated_at = $updated_at;

        return $this;
    }

    /**
     * @ORM\PrePersist
     * @ORM\PreUpdate
     */
    public function updatedTimestamps(): void
    {
        $this->setUpdatedAt(new \DateTime('now'));
        if ($this->getCreatedAt() === null) {
            $this->setCreatedAt(new \DateTime('now'));
        }
    }

    public function __toString() :String {
        return $this->getNomPrenom();
    }
}

src/Entity/Livre.php
<?php

namespace App\Entity;

use App\Repository\LivreRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Validator\Constraints as Assert;



/**
 * @ORM\Entity(repositoryClass=LivreRepository::class)
 * @ORM\HasLifecycleCallbacks()
 * @UniqueEntity(fields={"isbn"}, message="This ISBN13 key exists already")
 */
class Livre
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(name="isbn", type="string", length=17, unique=true)
     * @Assert\NotBlank(message="Enter the ISBN13 key")
     * @Assert\Isbn( type="isbn13", isbn13Message="Invalid ISBN-13 key")
     */
    private $isbn;

    /**
     * @ORM\Column(type="string", length=150)
     * @Assert\Length (max=150, maxMessage="Title length should be less than 150 character")
     */
    private $titre;

    /**
     * @ORM\Column(type="integer")
     * @Assert\NotNull(message="Enter number of pages")
     * @Assert\Positive(message="Invalid number of pages")
     */
    private $nombre_pages;

    /**
     * @ORM\Column(type="date")*
     * @Assert\NotNull(message="Set publushing Date")
     * @Assert\NotBlank(message="Set publushing Date")
     * @Assert\LessThan("today", message="Invalid Date")
     */
    private $date_de_parution;

    /**
     * @ORM\Column(type="smallint")
     * @Assert\NotNull(message="Enter the mark")
     * @Assert\PositiveOrZero(message="Invalid Mark")
     * @Assert\Range(
     *      min = 0,
     *      max = 20,
     *      notInRangeMessage = "Invalid Mark, it should be between {{ min }} & {{ max }}.",
     * )
     */
    private $note;

    /**
     * @ORM\ManyToMany(targetEntity=Auteur::class, inversedBy="livres")
     * @Assert\Count(min=1, minMessage="A book must be written by one author at least")
     */
    private $auteurs;

    /**
     * @ORM\ManyToMany(targetEntity=Genre::class, inversedBy="livres")
     * @Assert\Count(min=1, minMessage="A book must belong to one genre at least")
     */
    private $genres;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $image;

    /**
     * @ORM\Column(type="datetime")
     */
    private $created_at;

    /**
     * @ORM\Column(type="datetime")
     */
    private $updated_at;

    public function __construct()
    {
        $this->auteurs = new ArrayCollection();
        $this->genres = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getIsbn(): ?string
    {
        return $this->isbn;
    }

    public function setIsbn(string $isbn): self
    {
        $this->isbn = $isbn;

        return $this;
    }

    public function getTitre(): ?string
    {
        return $this->titre;
    }

    public function setTitre(string $titre): self
    {
        $this->titre = $titre;

        return $this;
    }

    public function getNombrePages(): ?string
    {
        return $this->nombre_pages;
    }

    public function setNombrePages(string $nombre_pages): self
    {
        $this->nombre_pages = $nombre_pages;

        return $this;
    }

    public function getDateDeParution(): ?\DateTimeInterface
    {
        return $this->date_de_parution;
    }

    public function setDateDeParution(\DateTimeInterface $date_de_parution): self
    {
        $this->date_de_parution = $date_de_parution;

        return $this;
    }

    public function getNote(): ?int
    {
        return $this->note;
    }

    public function setNote(int $note): self
    {
        $this->note = $note;

        return $this;
    }

    /**
     * @return Collection|Auteur[]
     */
    public function getAuteurs(): Collection
    {
        return $this->auteurs;
    }

    public function addAuteur(Auteur $auteur): self
    {
        if (!$this->auteurs->contains($auteur)) {
            $this->auteurs[] = $auteur;
            $auteur->addLivre($this);
        }

        return $this;
    }

    public function removeAuteur(Auteur $auteur): self
    {
        if ($this->auteurs->removeElement($auteur)) {
            $auteur->removeLivre($this);
        }

        return $this;
    }

    /**
     * @return Collection|Genre[]
     */
    public function getGenres(): Collection
    {
        return $this->genres;
    }

    public function addGenre(Genre $genre): self
    {
        if (!$this->genres->contains($genre)) {
            $this->genres[] = $genre;
        }

        return $this;
    }

    public function removeGenre(Genre $genre): self
    {
        $this->genres->removeElement($genre);

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(?string $image): self
    {
        $this->image = $image;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(\DateTimeInterface $updated_at): self
    {
        $this->updated_at = $updated_at;

        return $this;
    }

    /**
     * @ORM\PrePersist
     * @ORM\PreUpdate
     */
    public function updatedTimestamps(): void
    {
        $this->setUpdatedAt(new \DateTime('now'));
        if ($this->getCreatedAt() === null) {
            $this->setCreatedAt(new \DateTime('now'));
        }
    }
}

src/Controller/AuteurController.php
<?php

namespace App\Controller;

use App\Entity\Auteur;
use App\Form\AuteurType;
use App\Repository\AuteurRepository;
use App\Repository\LivreRepository;
use Doctrine\ORM\EntityManagerInterface;
use Doctrine\ORM\Query\Expr;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Console\Output\ConsoleOutput;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Intl\Countries;
use Symfony\Component\Routing\Annotation\Route;


class AuteurController extends AbstractController
{
    /**
     * @Route("/authors/api", name="auteur_api", methods={"GET"})
     */
    public function apiSuggestions(AuteurRepository $auteurRepository, Request $request) : Response {
        if( $this->getUser()==null )
            return $this->json([]);
        $value = trim($request->get('value'));
        if( strlen($value)>0 )
            $authors = $auteurRepository->createQueryBuilder('a')->where('a.nom_prenom LIKE :value')->setParameter('value', "%".$request->get('value')."%")->getQuery()->getResult() ;
        else
            $authors = [];
        $cut = function( Auteur $author){
            return ['nom_prenom'=>$author->getNomPrenom(), 'value'=> intval( $author->getId()), "image"=> $author->getImage()  ];
        };
        $authors = array_map( $cut, $authors );
        return $this->json($authors);
    }

    /**
     * @Route("/authors", name="auteur_index", methods={"GET"})
     */
    public function index(AuteurRepository $auteurRepository, Request $request, PaginatorInterface $paginator): Response
    {
        $this->denyAccessUnlessGranted("IS_AUTHENTICATED_FULLY");

        $search = trim ( $request->get('search') );
        $nationalityCode = trim ( $request->get('nationalityCode') );
        $nationalityCode = $nationalityCode=="-"? "":$nationalityCode;
        $submitted = trim ( $request->get('submitted') );

        $query = $auteurRepository->fastSearch( strlen($search)>0? $search:null, strlen($nationalityCode)>0? $nationalityCode:null );

        $authors = $paginator->paginate(
            $query,
            $request->query->getInt('page', 1), /*page number*/
            16 /*limit per page*/
        );

        $countries = Countries::getCountryCodes();

        return $this->render('auteur/userNavigation.html.twig', [
            'auteurs' => $auteurRepository->findAll(),
            'search' => $search,
            'nationalityCode' => $nationalityCode,
            'submitted' => $submitted,
            'authors' => $authors,
            'countries' => $countries,
            'order'=> $request->get('order'),
            'totalCount' => $authors->getTotalItemCount()
        ]);
    }

    /**
     * @Route("/cp/authors/new", name="auteur_new", methods={"GET", "POST"})
     */
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $auteur = new Auteur();
        $form = $this->createForm(AuteurType::class, $auteur);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($auteur);
            $entityManager->flush();
            $this->addFlash('created', 'true');
            return $this->redirectToRoute('auteur_show', ['id'=>$auteur->getId()], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('auteur/new.html.twig', [
            'auteur' => $auteur,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/authors/{id}", name="auteur_show", methods={"GET"})
     */
    public function show( Auteur $auteur, Request $request, PaginatorInterface $paginator, LivreRepository $livreRepository): Response
    {
        $this->denyAccessUnlessGranted("IS_AUTHENTICATED_FULLY");
        $books = $paginator->paginate(
            $livreRepository->createQueryBuilder('l')
                ->leftJoin('l.auteurs', 'a')
                ->where("a.id = :id")
                ->setParameter('id', $auteur->getId())->getQuery(),
            $request->query->getInt('page', 1), /*page number*/
            20 /*limit per page*/
        );
        return $this->render('auteur/show.html.twig', [
            'auteur' => $auteur,
            'books' => $books,
            'page' => $request->query->getInt('page', 1),
            'order' => $request->get('order')
        ]);
    }

    /**
     * @Route("/cp/authors/{id}/edit", name="auteur_edit", methods={"GET", "POST"})
     */
    public function edit(Request $request, Auteur $auteur, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(AuteurType::class, $auteur);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();
            $this->addFlash('editted', 'true');
            return $this->redirectToRoute('auteur_show', ['id'=>$auteur->getId()], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('auteur/edit.html.twig', [
            'auteur' => $auteur,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/cp/authors/{id}", name="auteur_delete", methods={"POST"})
     */
    public function delete(Request $request, Auteur $auteur, EntityManagerInterface $entityManager, LivreRepository $livreRepository, AuteurRepository $auteurRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$auteur->getId(), $request->request->get('_token'))) {
            $entityManager->remove($auteur);
            $this->addFlash('deleted', $auteur->getNomPrenom());
            $entityManager->flush();
            // delete books with no authors
            $booksWithAuthors = $livreRepository->createQueryBuilder('l')->select('l.id')->join('l.auteurs', 'a', Expr\Join::WITH, null)->distinct(true)->getQuery()->getScalarResult();
            for( $i=0; $i<count($booksWithAuthors); $i++)
                $booksWithAuthors[$i]= intval($booksWithAuthors[$i]['id']);
            dump( $booksWithAuthors);
            $booksWithNoWauthors = $livreRepository->createQueryBuilder('l')->select('l.id')->where(" l.id NOT IN (:arraOy) ")->setParameter("arraOy", $booksWithAuthors)->getQuery()->getResult();
            dump( $booksWithNoWauthors);
            foreach ( $booksWithNoWauthors as $book)
                $entityManager->remove( $livreRepository->find($book) );
            $entityManager->flush();
        }

        return $this->redirectToRoute('cp_auteur_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/auteur/_delete_form.html.twig
<form method="post" style="display: inline-block; width: fit-content; margin-left: auto;" action="{{ path('auteur_delete', {'id': auteur.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item? because if there are any books related only to this author, they will be deleted !');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ auteur.id) }}">
    <button class="ui button btn red" type="submit"> <i class="trash alternate icon"></i> Delete</button>
</form>

templates/auteur/index.html.twig
{% extends 'base.html.twig' %}

{% block title %} BookStore | CP : Authors {% endblock %}

{% block body %}

    <div class="contentWrapper">

        <div class="ui segment sixteen  column wide items" style="padding: 1em 1.5em; border: 1px solid gray; background-color: #fffffdc7;">
            <h5 class="ui header customClass pb-0">
                <a href="{{ path("cp_index") }}"> <i class="icon left arrow" ></i> Go Back to ControlPanel  </a>
            </h5>
            <h1 class="ui header center aligned customClass pt-0 orange huge"> Authors management </h1>
            {% set flashes = app.flashes('deleted')  %}
            {% if flashes %}
                <div class="ui green message">
                    <div class="header" style="text-align: center;">
                        Author "{{ flashes|join(' ') }}" was successfuly deleted
                    </div>
                </div>
            {% endif %}
        </div>

        <div class="ui segment sixteen  column wide items" style="padding: 1em 1.5em; border: 1px solid gray; background-color: #fffffdc7;">
            <div class="ui grid three column">
                <div class="ui column left floated">
                    <form action="{{ path('cp_auteur_index') }}" method="get">
                        <div class="ui action input fluid">
                            <input type="text" name="search" maxlength="50" value="{{ search }}" placeholder="Search with fullName, nationality...">
                            {% if search|length>0 %}
                                <a href="{{ path('cp_auteur_index') }}" class="ui icon button negative">
                                    <i class="times icon"></i>
                                </a>
                            {% endif %}
                            <button type="submit" class="ui icon button teal">
                                <i class="search icon"></i>
                            </button>
                        </div>
                    </form>
                </div>
                <div class="column right floated customClass text-right">
                    <a href="{{ path('auteur_new') }}" class="ui button positive"> <i class="icon plus"></i> Create new </a>
                </div>
            </div>


            <table class="ui selectable striped customClass table center middle aligned">
                <thead>
                <tr>
                    <th><strong> # </strong></th>
                    <th>
                        {% if authors.isSorted('a.nom_prenom') %}
                            <u class="purple">
                                {{ knp_pagination_sortable(authors, 'Full name', 'a.nom_prenom') }}
                            </u>
                            <i class="icon {{ order is same as ('asc')? 'chevron up':'chevron down' }}" ></i>
                        {% else %}
                            {{ knp_pagination_sortable(authors, 'Full name', 'a.nom_prenom') }}
                        {% endif %}
                    </th>
                    <th>
                        {% if authors.isSorted('a.sexe') %}
                        <u class="purple">
                            {{ knp_pagination_sortable(authors, 'Sexe', 'a.sexe') }}
                        </u>
                        <i class="icon {{ order is same as ('asc')? 'chevron up':'chevron down' }}" ></i>
                        {% else %}
                            {{ knp_pagination_sortable(authors, 'Sexe', 'a.sexe') }}
                        {% endif %}
                    </th>
                    <th>
                        {% if authors.isSorted('a.date_de_naissance') %}
                            <u class="purple">
                                {{ knp_pagination_sortable(authors, 'Birth date', 'a.date_de_naissance') }}
                            </u>
                            <i class="icon {{ order is same as ('asc')? 'chevron up':'chevron down' }}" ></i>
                        {% else %}
                            {{ knp_pagination_sortable(authors, 'Birth date', 'a.date_de_naissance') }}
                        {% endif %}
                    </th>
                    <th>
                        {% if authors.isSorted('a.nationalite') %}
                        <u class="purple">
                            {{ knp_pagination_sortable(authors, 'Nationality', 'a.nationalite') }}
                        </u>
                        <i class="icon {{ order is same as ('asc')? 'chevron up':'chevron down' }}" ></i>
                        {% else %}
                            {{ knp_pagination_sortable(authors, 'Nationality', 'a.nationalite') }}
                        {% endif %}
                    </th>
                    <th>Actions</th>
                </tr>
                </thead>
                <tbody>
                {% set i=0 %}
                {% for auteur in authors %}
                    {% set i=1+i %}
                    {% set gender = auteur.sexe is same as('M') ? 1:0 %}
                    <tr>
                        <td> <strong> {{ (currentPage-1)*25+i }} </strong></td>
                        <td>{{ auteur.nomPrenom }}</td>
                        <td> <i class="{{ gender==1 ? 'mars blue':'venus pink' }} icon"></i> {{ gender==1 ? 'Male':'Female' }}  </td>
                        <td>{{ auteur.dateDeNaissance ? auteur.dateDeNaissance|date('d/m/Y') : '' }}</td>
                        <td> <i class="{{ auteur.nationalite|lower }} flag"> </i> {{ auteur.nationalite|country_name }}</td>
                        <td>
                            <a href="{{ path('auteur_show', {'id': auteur.id}) }}" title="view">
                                <i class="icon eye teal"> </i>
                            </a>
                            <a href="{{ path('auteur_edit', {'id': auteur.id}) }}" title="Edit">
                                <i class="pencil alternate icon olive"></i>
                            </a>
                        </td>
                    </tr>
                {% else %}
                    <tr>
                        <td colspan="7">no records found</td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
        {% if authors|length>0 %}
            <div class="ui segment fourteen column wide center aligned" style=" margin-bottom: 2em !important; border: 1px solid gray; background-color: #fffffdc7;">
                {{ knp_pagination_render(authors) }}
            </div>
        {% endif %}

    </div>
{% endblock %}

templates/auteur/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}BookStore | Author: {{ auteur.nomPrenom }}{% endblock %}


{% block body %}
    <div class="contentWrapper" style="padding: 1em">
        <div class="ui segment sixteen column wide items" style="padding: 1em; border: 1px solid gray; background-color: #fffffdc7;">
            <div style="display: flex;align-content: center;justify-content: space-between;align-items: center;">
                <h5 class="ui header customClass pb-0 left aligned">
                    <a href="{{ path("auteur_index") }}"> <i class="icon left arrow" ></i> Go Back to authors list  </a>
                </h5>
                {% if is_granted('ROLE_ADMIN') %}
                    <div>
                        <a href="{{ path('cp_auteur_index') }}" class="ui button orange" style="display: inline-block; width: fit-content;" > <i class="list icon"></i>  list </a>
                        <a href="{{ path('auteur_edit', {'id': auteur.id}) }}" class="ui button olive" style="display: inline-block; width: fit-content;" > <i class="edit icon"></i> Edit </a>
                        {{ include('auteur/_delete_form.html.twig') }}
                    </div>
                {% endif %}
            </div>
        </div>

        <div class="ui segment sixteen column wide items" style="padding: 1em; border: 1px solid gray; background-color: #fffffdc7;">
            <div class="ui items">
                <div class="item" style=" padding: 1em 2.8em; margin: 0 auto;">
                    <div class="image">
                        <img src="{{ auteur.image }}">
                    </div>
                    <div class="content" style="flex-direction: column;display: flex;justify-content: center;">
                        <h1 class="ui header huge center aligned"> {{ auteur.nomPrenom }} </h1>
                        <div class="description">
                            <h3 class="ui header center aligned"> <strong style="text-decoration: underline; margin-right: 6px;" class="meta"> Sexe : </strong>  {{ auteur.sexe is same as ('M') ?'<span class="blue" > <i class="icon mars blue"></i> Male </span>':'<span class="pink"> <i class="pink icon venus"></i> Female </span>' }} </h3>
                            <h3 class="ui header center aligned"> <strong style="text-decoration: underline; margin-right: 6px;" class="meta"> Birth date : </strong> {{ auteur.dateDeNaissance|date('d/m/Y') }}  </h3>
                            <h3 class="ui header center aligned"> <strong style="text-decoration: underline; margin-right: 6px;" class="meta"> Nationality : </strong> <i class="flag {{ auteur.nationalite|lower }}"></i> {{ auteur.nationalite|country_name }}  </h3>
                            <h3 class="ui header center aligned"> <strong style="text-decoration: underline; margin-right: 6px;" class="meta"> Number of books : </strong>  {{ auteur.livres|length }}  </h3>
                        </div>
                        {% if is_granted('ROLE_ADMIN') %}
                            <div class="ui header small right bottom aligned " style="padding-top: 7em;">
                                <div class="extra brown">
                                    This author was created in : {{ auteur.createdAt|date('d/m/Y') }} , and editted last time in {{ auteur.updatedAt|date('d/m/Y') }}
                                </div>
                            </div>
                        {% endif %}
                        {% if app.flashes('editted')|length>0 %}
                            <div class="ui green message">
                                <div class="header" style="text-align: center;">
                                    Author changes were successfuly saved
                                </div>
                            </div>
                        {% endif %}
                        {% if app.flashes('created')|length>0 %}
                            <div class="ui green message">
                                <div class="header" style="text-align: center;">
                                    Author created successfuly
                                </div>
                            </div>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>

        <div class="ui segment sixteen attached column wide items" style="padding: 1em; border: 1px solid gray;">
            <h3 class="ui header center aligned"> Author's books :  </h3>
        </div>
        <div class="ui segment sixteen attached column wide items" style="padding: 0em; border: 1px solid gray;">
            <table class="ui table striped customClass">
                <thead>
                <tr>
                    <th> <strong> # </strong> </th>
                    <th>
                        {% if books.isSorted('l.titre') %}
                            <u class="purple">
                                {{ knp_pagination_sortable(books, 'Title', 'l.titre') }}
                            </u>
                            <i class="icon {{ order is same as ('asc')? 'chevron up':'chevron down' }}" ></i>
                        {% else %}
                            {{ knp_pagination_sortable(books, ' Title', 'l.titre') }}
                        {% endif %}
                    </th>
                    <th>
                        {% if books.isSorted('l.nombre_pages') %}
                            <u class="purple">
                                {{ knp_pagination_sortable(books, 'Number of pages', 'l.nombre_pages') }}
                            </u>
                            <i class="icon {{ order is same as ('asc')? 'chevron up':'chevron down' }}" ></i>
                        {% else %}
                            {{ knp_pagination_sortable(books, ' Number of pages', 'l.nombre_pages') }}
                        {% endif %}
                    </th>
                    <th> Link </th>
                </tr>
                </thead>
                <tbody>
                {% set i=1 %}
                {% for book in books %}
                    <tr>
                        <td> {{ (page-1)*20+i }} </td>
                        <td> {{ book.titre }} </td>
                        <td> {{ book.nombrePages }} </td>
                        <td> <a href="{{ path('livre_show', {id:book.id}) }}" target="_blank"> <i class="icon linkify"></i> </a> </td>
                    </tr>
                    {% set i=i+1 %}
                {% else %}
                    <tr>
                        <td colspan="4" class="ui orange"> no Book found for this author </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
        {% if books|length>0 %}
            <div class="ui segment sixteen attached column wide items" style="padding: 1em; border: 1px solid gray; text-align: center;">
                {{ knp_pagination_render(books) }}
            </div>
        {% endif %}



    </div>

{% endblock %}